#!/usr/bin/env node
// Builds feed.xml (RSS 2.0) at the site root from posts/index.html.
//
// posts/index.html is the single source of truth for the post list — the
// same assumption js/random-post.js and js/post-filters.js already make —
// so this script re-parses its .post-card markup instead of keeping a
// second list of posts anywhere. Re-run it whenever a post is added,
// removed, or reordered in posts/index.html:
//
//   node scripts/build-feed.js
//
// No npm dependencies: the site has none, and posts/index.html's markup is
// generated by this same project in a single consistent shape, so a small
// regex-based scrape is simpler than pulling in an HTML parser for it.
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");

// The site's canonical base URL. Not present anywhere in the HTML itself
// (only in README.md's "Website URL" line) since it's a GitHub Pages
// *project* page (served from a /cmpa-4303/ subpath, not a custom domain
// at root) — update this if that ever changes.
const SITE_URL = "https://chgermai.github.io/cmpa-4303/";
const MAX_ITEMS = 50;

const MONTHS = {
  Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
  Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11,
};

function escapeXml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function stripTags(html) {
  return html.replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim();
}

// "Aug 2026" -> RFC 822 pubDate string. Posts are only ever dated to the
// month (see docs/post-search.md), so every item's pubDate is pinned to
// the 1st of its month at 00:00 UTC — accurate to the month, not the day,
// because no finer-grained date exists anywhere in the site's data.
function monthYearToPubDate(text) {
  const match = text.trim().match(/^([A-Za-z]{3})\s+(\d{4})$/);
  if (!match) {
    throw new Error(`Unrecognized date "${text}" (expected e.g. "Aug 2026")`);
  }
  const [, monthAbbr, year] = match;
  const monthIndex = MONTHS[monthAbbr];
  if (monthIndex === undefined) {
    throw new Error(`Unrecognized month "${monthAbbr}" in date "${text}"`);
  }
  return new Date(Date.UTC(Number(year), monthIndex, 1)).toUTCString();
}

function readHomepageMeta(homepageHtml) {
  const titleMatch = homepageHtml.match(/<h1>([^<]+)<\/h1>/);
  const subtitleMatch = homepageHtml.match(
    /<p class="subtitle">\s*([\s\S]*?)\s*<\/p>/,
  );
  if (!titleMatch || !subtitleMatch) {
    throw new Error("Could not read <h1> / .subtitle from index.html");
  }
  return {
    title: stripTags(titleMatch[1]),
    description: stripTags(subtitleMatch[1]),
  };
}

// Parses posts/index.html's .post-card markup — the same source
// js/post-filters.js reads in the browser — into plain objects. Cards are
// already listed newest-first (see docs/post-filters-sidebar.md), so the
// order read here is already the feed order.
function readPosts(postsIndexHtml) {
  const cardRe = /<li class="post-card"[^>]*>([\s\S]*?)<\/li>/g;
  const posts = [];
  let cardMatch;
  while ((cardMatch = cardRe.exec(postsIndexHtml))) {
    const card = cardMatch[1];

    const hrefMatch = card.match(/class="post-card-link"\s+href="([^"]+)"/);
    const titleMatch = card.match(
      /class="post-card-title">([\s\S]*?)<\/h2>/,
    );
    const dateMatch = card.match(
      /class="post-card-date">([\s\S]*?)<\/p>/,
    );
    const descMatch = card.match(
      /class="post-card-desc">([\s\S]*?)<\/p>/,
    );

    if (!hrefMatch || !titleMatch || !dateMatch || !descMatch) {
      throw new Error(
        "A .post-card in posts/index.html is missing an expected field:\n" +
          card.slice(0, 200),
      );
    }

    posts.push({
      href: hrefMatch[1].replace(/^\.\//, ""), // "./01-foo.html" -> "01-foo.html"
      title: stripTags(titleMatch[1]),
      dateText: stripTags(dateMatch[1]),
      description: stripTags(descMatch[1]),
    });
  }
  return posts;
}

function buildItemXml(post) {
  const url = SITE_URL + "posts/" + post.href;
  const pubDate = monthYearToPubDate(post.dateText);
  return [
    "    <item>",
    `      <title>${escapeXml(post.title)}</title>`,
    `      <link>${escapeXml(url)}</link>`,
    `      <guid isPermaLink="true">${escapeXml(url)}</guid>`,
    `      <pubDate>${pubDate}</pubDate>`,
    `      <description>${escapeXml(post.description)}</description>`,
    "    </item>",
  ].join("\n");
}

function buildFeedXml({ title, link, description }, posts) {
  const items = posts.map(buildItemXml).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>${escapeXml(title)}</title>
    <link>${escapeXml(link)}</link>
    <description>${escapeXml(description)}</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${items}
  </channel>
</rss>
`;
}

function main() {
  const homepageHtml = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  const postsIndexHtml = fs.readFileSync(
    path.join(ROOT, "posts", "index.html"),
    "utf8",
  );

  const meta = readHomepageMeta(homepageHtml);
  const allPosts = readPosts(postsIndexHtml);
  const posts = allPosts.slice(0, MAX_ITEMS);

  const xml = buildFeedXml(
    { title: meta.title, link: SITE_URL, description: meta.description },
    posts,
  );

  fs.writeFileSync(path.join(ROOT, "feed.xml"), xml);
  console.log(
    `Wrote feed.xml with ${posts.length} item(s)` +
      (allPosts.length > MAX_ITEMS
        ? ` (of ${allPosts.length} total, capped at ${MAX_ITEMS})`
        : "") +
      ".",
  );
}

main();
